### ISSUE TITLE
Location of binaries

### ISSUE THREAD

**Issue by virtualstaticvoid** [virtualstaticvoid/asdf-kubebuilder#1]
As per the `kubebuilder` [installation guide](https://book.kubebuilder.io/getting_started/installation_and_setup.html), the binaries and other files have to be located in `/usr/local/kubebuilder/bin`.

Doesn't seem that this constraint will be removed, as mentioned in [kubebuilder issue #326](https://github.com/kubernetes-sigs/kubebuilder/issues/326).

**Comment by tobbbles** [comment]
Note that an envvar has been introduced to tell kubebuilder where to look for it's binary assets.
https://github.com/kubernetes-sigs/kubebuilder/issues/326#issuecomment-431365391

**Comment by RafalSkolasinski** [comment]
Yes, adding information about required environmental variable in readme would be good. On fish I do
```
set -x KUBEBUILDER_ASSETS (asdf where kubebuilder)"/bin"
```

**Comment by RafalSkolasinski** [comment]
Bash equivalent would be
```
export KUBEBUILDER_ASSETS=$(asdf where kubebuilder)"/bin"
```

**Comment by virtualstaticvoid** [comment]
I'm going to explore using a [custom shim template](https://asdf-vm.com/#/plugins-create?id=custom-shim-templates) to set the `KUBEBUILDER_ASSETS` environment variable and then call out to the actual executable, so that users get the same experience as with other asdf plugins.

**Comment by virtualstaticvoid** [comment]
@RafalSkolasinski The custom shim works a treat!
I've merged the PR with the changes.

**Comment by RafalSkolasinski** [comment]
Nice, gonna check it soon then :)
