### ISSUE TITLE
add this to upstream

### ISSUE THREAD

**Issue by RafalSkolasinski** [virtualstaticvoid/asdf-kubebuilder#3]
Any reason why this plugin wouldn't be commited upstream? 
It is the only `asdf` plugin I need to add manually ; - )

Would be great to see it on the official list: https://asdf-vm.com/#/plugins-all

If I am not mistaken here is the right place to contribute it: https://github.com/asdf-vm/asdf-plugins

**Comment by virtualstaticvoid** [comment]
Added https://github.com/asdf-vm/asdf-plugins/pull/355 PR.

**Comment by virtualstaticvoid** [comment]
PR https://github.com/asdf-vm/asdf-plugins/pull/355 has been merged, and plugin is listed after updating.

```
$ asdf plugin-list-all | grep kubebuilder
kubebuilder                   https://github.com/virtualstaticvoid/asdf-kubebuilder.git
```

**Comment by RafalSkolasinski** [comment]
Nice, thanks a lot for this!
