### ISSUE TITLE
Beta releases asset name change

### ISSUE THREAD

**Issue by tobbbles** [virtualstaticvoid/asdf-kubebuilder#4]
Hello hello, firstly thank you for providing this asdf-vm plugin, it's much appreciated.

I just wanted to open an issue to raise awareness that the v3.0.0 beta releases of kubebuilder do not follow the asset naming convention of `kubebuilder_X.Y.Z_linux_arm64.tar.gz` but rather completely omit the versioning information altogether.

As such, it is not possible to install beta releases through asdf-kubebuilder. 

I understand that branching on this inconsistency in the plugin may be quite troublesome, and not something that one wants to tackle here. What are peoples thoughts on handing beta releases?

**Comment by virtualstaticvoid** [comment]
Hi @tobbbles 
Thanks for the heads up. I'll make provision for the new asset naming convention.
For other asdf-plugins, such as [asdf-k9s](https://github.com/virtualstaticvoid/asdf-k9s) I've handled such changes with [version checks](https://github.com/virtualstaticvoid/asdf-k9s/blob/master/bin/install#L48) in the bash script, which isn't ideal of course, but there doesn't seem to be a better way to solve it as asdf doesn't manage versions of plugins as such.
